import type { Property } from '@connecker/shared-types';

export const FEATURED_PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Villa moderne avec piscine',
    description: 'Magnifique villa contemporaine avec piscine, jardin paysager et vue imprenable.',
    property_type: 'villa',
    transaction_type: 'sale',
    status: 'published',
    price: 285000000,
    currency: 'XOF',
    surface_area: 350,
    rooms: 7,
    bedrooms: 4,
    bathrooms: 3,
    address: 'Almadies',
    city: 'Dakar',
    district: 'Almadies',
    country: 'SN',
    features: ['Piscine', 'Jardin', 'Garage', 'Climatisation'],
    images: [{ id: '1', url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80', is_primary: true, order: 0 }],
    announcer_id: 'u1',
    views_count: 234,
    leads_count: 12,
    expires_at: '2026-07-07',
    created_at: '2026-04-01',
    updated_at: '2026-04-01',
  },
  {
    id: '2',
    title: 'Appartement T3 standing Plateau',
    description: 'Bel appartement de standing au coeur du Plateau, entierement renove.',
    property_type: 'apartment',
    transaction_type: 'rent',
    status: 'published',
    price: 850000,
    currency: 'XOF',
    surface_area: 95,
    rooms: 4,
    bedrooms: 2,
    bathrooms: 2,
    floor: 5,
    total_floors: 8,
    address: 'Rue Carnot',
    city: 'Dakar',
    district: 'Plateau',
    country: 'SN',
    features: ['Ascenseur', 'Balcon', 'Gardien', 'Parking'],
    images: [{ id: '2', url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80', is_primary: true, order: 0 }],
    announcer_id: 'u2',
    views_count: 189,
    leads_count: 8,
    expires_at: '2026-07-07',
    created_at: '2026-04-02',
    updated_at: '2026-04-02',
  },
  {
    id: '3',
    title: 'Terrain constructible Saly',
    description: 'Beau terrain bien situe a Saly, ideal pour projet residentiel ou touristique.',
    property_type: 'land',
    transaction_type: 'sale',
    status: 'published',
    price: 45000000,
    currency: 'XOF',
    surface_area: 500,
    rooms: 0,
    bedrooms: 0,
    bathrooms: 0,
    address: 'Saly Portudal',
    city: 'Mbour',
    district: 'Saly',
    country: 'SN',
    features: ['Titre foncier', 'Viabilise', 'Bord de route'],
    images: [{ id: '3', url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80', is_primary: true, order: 0 }],
    announcer_id: 'u3',
    views_count: 156,
    leads_count: 15,
    expires_at: '2026-07-07',
    created_at: '2026-04-03',
    updated_at: '2026-04-03',
  },
  {
    id: '4',
    title: 'Maison familiale Ngor',
    description: 'Grande maison familiale avec terrasse et vue sur mer a Ngor.',
    property_type: 'house',
    transaction_type: 'sale',
    status: 'published',
    price: 180000000,
    currency: 'XOF',
    surface_area: 250,
    rooms: 6,
    bedrooms: 4,
    bathrooms: 2,
    address: 'Ngor',
    city: 'Dakar',
    district: 'Ngor',
    country: 'SN',
    features: ['Terrasse', 'Vue mer', 'Garage double'],
    images: [{ id: '4', url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80', is_primary: true, order: 0 }],
    announcer_id: 'u1',
    views_count: 312,
    leads_count: 21,
    expires_at: '2026-07-07',
    created_at: '2026-04-04',
    updated_at: '2026-04-04',
  },
  {
    id: '5',
    title: 'Studio meuble Mermoz',
    description: 'Studio entierement meuble et equipe, ideal pour jeune professionnel.',
    property_type: 'studio',
    transaction_type: 'rent',
    status: 'published',
    price: 350000,
    currency: 'XOF',
    surface_area: 35,
    rooms: 1,
    bedrooms: 1,
    bathrooms: 1,
    floor: 2,
    address: 'Mermoz',
    city: 'Dakar',
    district: 'Mermoz',
    country: 'SN',
    features: ['Meuble', 'Wifi', 'Climatisation'],
    images: [{ id: '5', url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80', is_primary: true, order: 0 }],
    announcer_id: 'u2',
    views_count: 98,
    leads_count: 5,
    expires_at: '2026-07-07',
    created_at: '2026-04-05',
    updated_at: '2026-04-05',
  },
  {
    id: '6',
    title: 'Bureau open space Plateau',
    description: 'Espace de bureau moderne en open space au centre du Plateau.',
    property_type: 'office',
    transaction_type: 'rent',
    status: 'published',
    price: 1200000,
    currency: 'XOF',
    surface_area: 120,
    rooms: 3,
    bedrooms: 0,
    bathrooms: 1,
    floor: 3,
    address: 'Avenue Leopold Sedar Senghor',
    city: 'Dakar',
    district: 'Plateau',
    country: 'SN',
    features: ['Climatisation', 'Fibre optique', 'Parking', 'Securite'],
    images: [{ id: '6', url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80', is_primary: true, order: 0 }],
    announcer_id: 'u3',
    views_count: 67,
    leads_count: 3,
    expires_at: '2026-07-07',
    created_at: '2026-04-06',
    updated_at: '2026-04-06',
  },
];

export const POPULAR_CITIES = [
  { name: 'Dakar', count: 1243, image: 'https://images.unsplash.com/photo-1611348524140-53c9a25263d6?w=600&q=80' },
  { name: 'Saint-Louis', count: 342, image: 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=600&q=80' },
  { name: 'Thies', count: 287, image: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=600&q=80' },
  { name: 'Mbour', count: 456, image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80' },
];

export const PROPERTY_TYPES = [
  { type: 'apartment', label: 'Appartements', icon: '🏢', count: 892 },
  { type: 'house', label: 'Maisons', icon: '🏠', count: 654 },
  { type: 'villa', label: 'Villas', icon: '🏡', count: 321 },
  { type: 'land', label: 'Terrains', icon: '🌍', count: 478 },
  { type: 'studio', label: 'Studios', icon: '🛏️', count: 256 },
  { type: 'office', label: 'Bureaux', icon: '🏬', count: 134 },
];
